---
title: "Statistical Analysis of 2012 Expression data"
author: "John T. Lovell"
date: "1-February 2016"
output:
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r, include=FALSE}
# Don't delete this chunk if you are using the mosaic package
# This loads the mosaic and dplyr packages
require(mosaic)
```

```{r, include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).

# This changes the default colors in lattice plots.
trellis.par.set(theme=theme.mosaic())  

# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
```

```{r, include=FALSE}
# Load additional packages here.  Uncomment the line below to use Project MOSAIC data sets.
# require(mosaicData)   
```

```{r, include=FALSE} 
library(devtools)
install_github("jtlovell/physGenomicsPVFinal")
library(physGenomicsPVFinal)
```

```{r}
library(physGenomicsPVFinal)
rm(list=ls())
data(tmpwfc20132014_3treatments)

### for conviencence, rename info and counts
info<-info1314
counts<-counts1314

### cull to high and low, given bad mean data at WFC
phys.lines<-which(info$Treatment != "mean")
counts<-counts[,phys.lines]
info<-info[phys.lines,]
info$Treatment<-factor(info$Treatment, levels=c("low","high"))
info$LocTrtYear<-as.factor(as.character(info$LocTrtYear))
#################################
# Part 2.1: Full model
#################################
stats<-pipeLIMMA(counts=counts, info=info, block=info$sb_unique, formula="~ Treatment * Location + Year + order")
voom.trtByMonth<-stats$voom[["E"]]
stats.fullmodel<-stats$simpleStats
stats.allests<-stats$stats

#################################
# Part 1.2: All pairwise contrasts
#################################
## Generate a design matrix that specifies all relavant contrasts
design <- model.matrix(~ 0+LocTrtYear + order , data=info)
colnames(design)<-gsub(c("LocTrtYear"),c("trt"), colnames(design))
contrast.matrix <- makeContrasts(trtTMP_high_2013-trtTMP_low_2013, trtTMP_high_2014-trtTMP_low_2014,
                                 trtWFC_high_2013-trtWFC_low_2013, trtWFC_high_2014-trtWFC_low_2014,
                                 levels=design)
lim.contrasts<-anovaLIMMA(counts=counts, design=design, block=info$Sub_Block, contrast.matrix=contrast.matrix)

#################################
# Part 1.3: Run PCA
#################################
pca<-DESeq2PCA(counts=counts, info=info, formula="~ Treatment * Location + Year + order",
               factors2Plot=c("Treatment", "Location", "Year"),
               factors2Extract=c("Treatment", "Location", "Year","order","MDWP", "PDWP","ID"))

#################################
# Part 1.4: Run model with MDWP as the predictor
#################################
stats<-pipeLIMMA(counts=counts, info=info, block=info$Sub_Block, formula="~ MDWP * Location + Year + order")
stats.fullmodel.mdwp<-stats$simpleStats
stats.allests.mdwp<-stats$stats

#################################
# Part 1.5: Run model with MDWP as the predictor, without controlling for location or year
#################################
stats<-pipeLIMMA(counts=counts, info=info, block=info$Sub_Block, formula="~ MDWP + order")
stats.fullmodel.mdwponly<-stats$simpleStats
stats.allests.mdwponly<-stats$stats

#save(stats.fullmodel, stats.allests, lim.contrasts, pca, voom.trtByMonth,
#     stats.fullmodel.mdwp, stats.allests.mdwp, stats.fullmodel.mdwponly, stats.fullmodel.mdwponly,
#     file="/Users/John/Desktop/dropbox/Switchgrass_PlantPhys/stats_output/shelter201314_allstats.RData")
```
