---
title: "Statistical Analysis of Cylinder Expression data"
author: "John T. Lovell"
date: "2-February 2016"
output:
  html_document:
    fig_height: 8
    fig_width: 8
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r, include=FALSE}
# Don't delete this chunk if you are using the mosaic package
# This loads the mosaic and dplyr packages
require(mosaic)
```

```{r, include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).

# This changes the default colors in lattice plots.
trellis.par.set(theme=theme.mosaic())  

# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
```

```{r, include=FALSE}
# Load additional packages here.  Uncomment the line below to use Project MOSAIC data sets.
# require(mosaicData)   
```

```{r, include=FALSE} 
library(devtools)
install_github("jtlovell/physGenomicsPVFinal")
library(physGenomicsPVFinal)
```

```{r}
library(physGenomicsPVFinal)
rm(list=ls())
data(potsGreenhouse)

info<-info.wetdry
counts<-counts.wetdry


library(qdap)
info$Treatment<-multigsub(c("control","drought","14d","13d","5AM","10AM","12PM","2PM"),
                          c("w","d","d1","d2","t0","t5","t7","t9"),
                          as.character(info$Treatment))
info$Time<-multigsub(c("control","drought","14d","13d","5AM","10AM","12PM","2PM"),
                          c("w","d","d1","d2","t0","t5","t7","t9"),
                          as.character(info$Time))
info$Day<-multigsub(c("control","drought","14d","13d","5AM","10AM","12PM","2PM"),
                          c("w","d","d1","d2","t0","t5","t7","t9"),
                          as.character(info$Day))
info$time_day_try<-as.factor(with(info, paste(Treatment,Day,Time, sep="_")))
info$Treatment<-factor(info$Treatment, levels=c("w","d"))
info$Time<-factor(info$Time, levels=c("t0", "t5", "t7", "t9"))
info$Day<-factor(info$Day, levels=c("d1","d2"))
#################################
# Part 1: Full model
#################################
stats<-pipeLIMMA(counts=counts, info=info, block=info$id, formula="~ Treatment * Time + Day")
v<-stats$voom[["E"]]
stats.fullmodel<-stats$simpleStats
stats.allests<-stats$stats

#################################
# Part 2: Run PCA
#################################
pca<-voom2PCA(v=v, info=info, ids=info$id)
library(ggplot2)
ggplot(pca, aes(x=PC1, y=PC2, col=Day, shape=Treatment))+theme_bw() +facet_wrap(~Time)+
  geom_point(size=4)+scale_shape_manual(values=c(2,19))

#################################
# Part 3: All pairwise contrasts
#################################
## Generate a design matrix that specifies all relavant contrasts
f<-info$time_day_try
design <- model.matrix(~0+f)
contrast.matrix<-makeContrasts(fw_d1_t0-fd_d1_t0, fw_d1_t5-fd_d1_t5, fw_d1_t7-fd_d1_t7,fw_d1_t9-fd_d1_t9,
                               fw_d2_t0- fd_d2_t0, fw_d2_t9- fd_d2_t9,
                               levels=design)
lim.contrasts<-anovaLIMMA(counts=counts, design=design, block=info$id, contrast.matrix=contrast.matrix)
```
